<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Include="..\..\GTe.ico" Link="GTe.ico" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\GT001.Editor.Core\GT001.Editor.Core.csproj" />
    <ProjectReference Include="..\GT001.Editor.Midi\GT001.Editor.Midi.csproj" />
    <ProjectReference Include="..\GT001.Editor.Protocol\GT001.Editor.Protocol.csproj" />
    <ProjectReference Include="..\GT001.Editor.Storage\GT001.Editor.Storage.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\GTe.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

</Project>
